#################################################
# Playbooks: Docker and docker-compose
# install mc and add user defined in vars to docker group
#################################################
---
- hosts: docker
  become: false
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - lsb-release
        - gnupg
        - mc

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable
        state: present

    - name: Update apt and install docker-ce
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']

    - name: Add remote user to "docker" group
      user:
        name: "{{ user }}"
        groups: "docker"
        append: yes

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
